//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficNow.Service.Implementation {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class ServiceSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ServiceSettings defaultInstance = ((ServiceSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ServiceSettings())));
        
        public static ServiceSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AKIAI5B74QQSXUSBNH3A")]
        public string SMTP_USERNAME {
            get {
                return ((string)(this["SMTP_USERNAME"]));
            }
            set {
                this["SMTP_USERNAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aoj+tOrMytJU2QYkKS/51Syq/nefeBXgcZ8BmE/9mfnf")]
        public string SMTP_PASSWORD {
            get {
                return ((string)(this["SMTP_PASSWORD"]));
            }
            set {
                this["SMTP_PASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("email-smtp.us-west-2.amazonaws.com")]
        public string SMTP_HOST {
            get {
                return ((string)(this["SMTP_HOST"]));
            }
            set {
                this["SMTP_HOST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("587")]
        public int SMTP_PORT {
            get {
                return ((int)(this["SMTP_PORT"]));
            }
            set {
                this["SMTP_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyB9WCL0T_yJKerl-SDkzu8C2HlG4K_gY98")]
        public string GCM_KEY {
            get {
                return ((string)(this["GCM_KEY"]));
            }
            set {
                this["GCM_KEY"] = value;
            }
        }
    }
}
